[tool.poetry]
name = "cifra-cesar"
version = "0.1.0"
description = "Implementação da Cifra de César."
authors = ["Kaio Rocha <kaiodtr@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
